### PR TITLE
Cythonized some more code to make debugger faster

### PR DESCRIPTION
**Pull request by fitermay**
Cythonized some more code to make debugger faster

### CODE REVIEW

**Comment by fitermay** [comment]
First optimization speed up:
 cythonized method_calls_with_breakpoint benchmark by 15% 
 cythonized method_calls_with_step_over benchmark  by 20%

Second speeds up cythonized method_calls_without_breakpoint by 10%-20%, getting large variance with this benchmark.

**Comment by fitermay** [comment]
Also, I'd like to ask you to keep the code for Python 2.6 support. Where I work we have several thousand devs and internal users on Py 2.6. It's probably going to be another year until we can move off it.

**Comment by fabioz** [comment]
Just to note, haven't applied this because of current conflicts... also, I'm not sure it'll make such a difference anymore (given the latest performance related changes, I'm not sure this patch will still have the benefits it previously did, so, if you plan on working on it, it'd be nice to check if there are actually performance gains by running the debugger performance tests with/without this PR).

**Comment by fitermay** [comment]
This is obsolete. Closing.

**Pull request closed without merging**
