### PR TITLE
Make run_python_code_{mac,linux} quote safe

### PR DESCRIPTION
**Pull request by sorenh**

### CODE REVIEW

**Comment by fabioz** [comment]
Thanks for the fixes.

**Comment by fabioz** [comment]
@sorenh I had to revert the changes because the ci wasn't really passing after them and I failed to check that properly before merging (so, I'm waiting for further changes if you want to provide a new version).

**Comment by sorenh** [comment]
I'm sorry, I didn't see your comment until just now. Did you fix it or is it still outstanding? I tested on both Macn and Linux, so if it's still causing problems, where can I see the failures?

**Comment by fabioz** [comment]
You can see the failures from this pull request in: https://travis-ci.org/github/fabioz/PyDev.Debugger/builds/701221311

**Comment by fabioz** [comment]
p.s.: I just reverted the pull request,

**Pull request merged**
