### PR TITLE
Pydevd extensions PR #2

### PR DESCRIPTION
**Pull request by fitermay**
Resubmitting PR from pydevd_plugins fork after adding default for 'use_value_repr_instead_of_str'

### CODE REVIEW

**Comment by fabioz** [comment]
I was thinking a bit more about this and I think we could have a better solution now with the extensions... What do you think about removing that 'use_value_repr_instead_of_str' flag altogether and just giving an StrPresentationProvider in an extension which will do a repr on this case? 

The major work is probably creating a specific test for this situation (which I think is not currently covered), but it should a better solution... what do you think? Would you be willing to do implement that?

**Comment by fitermay** [comment]
It also occured to me that this is the correct approach but I'd rather send a seperate PR for that. There are enough changes here already IMO.

**Comment by fitermay** [comment]
By the way, Jetbrains must have tests for Django but in Professional Edition Java code.  Can they provide you with their test code so that we can port them to Python?

**Comment by fitermay** [comment]
Ok, I implemented it after all.  There is some copy-pasta here though.

**Pull request merged**
