### PR TITLE
Improve performance overhead for functions without breakpoints

### PR DESCRIPTION
**Pull request by fitermay**
This improves the overhead by about 40% by solving the problem
of making PyDBFrame a cdef

### CODE REVIEW

**Comment by fabioz** [comment]
Thanks for the patch. It seems Ok, I'll integrate it after I run some other tests. 

As a note, I'm also on the process of doing other performance improvements -- but in the case where there's actually a hit in the frame -- so, with this patch, both the traced and untraced sections should be faster ;)

**Comment by fabioz** [comment]
As a note, I've integrated the pull request... actual gains on the test case here showed around 20-30% improvement on the case where it runs without any breakpoint.

Also, I hope it'll fix the issue outlined at https://github.com/fabioz/PyDev.Debugger/issues/70 .

**Comment by fitermay** [comment]
I'm guessing it's machine and interpreter dependent. I'm measuring around 40% on my windows machine and Python 2.7.9.  Also how are you computing speedup? I use old_time/new_time - 1

**Comment by fabioz** [comment]
It's probably test-dependent... I'm using Python 2.7.12 (running the performance test: https://github.com/fabioz/PyDev.Debugger/blob/master/tests_python/performance_check.py -- the related test is the one which will print "method_calls_without_breakpoint")

**Pull request merged**
