### PR TITLE
Issue 85: Optimize var_to_xml

### PR DESCRIPTION
**Pull request by fitermay**
This should significantly speed up the performance of XML marshalling.

### CODE REVIEW

**Comment by fabioz** [comment]
Hi there, sorry about the delay. Just reviewed the patch... 

The major issue for integrating is that there are no tests in the patch (it actually introduced a bug where `>` is being changed to `<`).

Other minors:

- xml_quote_2 should probably be rename to xml_quote_preserve_tab (instead of xml_quote_2).

- the `def translator` is always converting to bytes, even on py3... I don't think this is consistent with the current quoting (a test should validate this -- as it is I believe you'll have encoding issues, so, make sure you test with values out the ascii range and also with invalid utf-8).

**Comment by fitermay** [comment]
Didn't include tests because it is implicitly tested by other debugger tests expecting certain XML. Now that you point out the bug I do see your point. I write independent tests for this.

**Comment by fabioz** [comment]
Closing this... I plan to investigate on different protocols in the future, so, this may not end up being as relevant.

**Comment by fitermay** [comment]
Sorry, did not get time to work on this

**Pull request closed without merging**
