### PR TITLE
Handle exception thrown when executing invalid expression

### PR DESCRIPTION
**Pull request by lukejriddle**
If an invalid expression is evaluated, the attempt to exec said expression results in an exception. Since the code omits an `except` clause and only does `try` `finally`, the exception is not properly discarded without a `return`, `break`, or `continue` statement: [reference](https://docs.python.org/3/reference/compound_stmts.html#finally-clause).

This resulted in the debugger hanging indefinitely when an invalid expression was evaluated. The exception would show in the console, but the stepping/continuing would stop working. 

~This PR fixes this issue by adding the `except` clause and logging the exception. This allows the debugger to continue executing.~

This PR fixes this issue by properly handling the exception in the calling method (see comments below)

### CODE REVIEW

**Comment by lukejriddle** [comment]
I should note that this only happens when [`internal_set_expression_json`](https://github.com/fabioz/PyDev.Debugger/blob/main/_pydevd_bundle/pydevd_comm.py#L1323) is called -- as part of a `setExpression` DAP call -- and that this issue doesn't occur when [`internal_evaluate_expression_json`](https://github.com/fabioz/PyDev.Debugger/blob/main/_pydevd_bundle/pydevd_comm.py#L1146) is called -- from the repl.

This is because the former [expects a return value from `evaluate_expression`](https://github.com/fabioz/PyDev.Debugger/blob/main/_pydevd_bundle/pydevd_comm.py#L1336), but that function will never return anything since `is_exec=True`. This results in the error check always failing. The latter properly wraps it in a try except.

**Comment by lukejriddle** [comment]
It also appears that if [`is_error`](https://github.com/fabioz/PyDev.Debugger/blob/main/_pydevd_bundle/pydevd_comm.py#L1339) were ever actually true, which it never will be since the function doesn't return anything, there'd be a runtime exception. [`Creating a SetExpressionResponseBody`](https://github.com/fabioz/PyDev.Debugger/blob/main/_pydevd_bundle/pydevd_comm.py#L1317) is done improperly; it expects `value` in the constructor.

**Comment by lukejriddle** [comment]
Added a new commit to address the above ^

**Comment by fabioz** [comment]
Sorry for the long time to review this. The change seems fine. Do you think you can fix the conflicts and resubmit?

**Comment by lukejriddle** [comment]
Done, thanks.

**Comment by fabioz** [comment]
Just merged. Thanks for the PR.

**Pull request merged**
